//----------------------------------------------------------------
//
// Function Name:     GetHref(HrefArray, LinksArray)
//
// January 19, 2023 - By: C.M. Jones
//
// This javascript gets all of the "href" properties 
// associated with all of the 'a' tags on a web page
//
// -------------
// Dependencies:
// -------------
//
// function GetLinks(
//
// ----------
// Arguments:
// ----------
// 
// [ HrefArray ]
// 
// This is the output array, or in other words, the return value
// and what is generated by this function
// 
// [ LinksArray ]
//
// This is the value that is generated by the GetLinks() function.
// 
//---------------------------------------------------------------- 

let ___al = {};

let ___HrefArray = {};

function GetHref(HrefArray, LinksArray) {

    let linksArray = LinksArray;

    for (let index = 0; index < linksArray.length; index++) {
        HrefArray[index] = linksArray[index].href
    }

    return HrefArray;

}

GetHref(___HrefArray, ___al);



